[package]
name = "subjective-logic"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
thiserror = "1.0"
approx = "0.5"
